### ISSUE TITLE
ESC key conflicts with vscode default behaviour

### ISSUE THREAD

**Issue by fengzhou0x** [jpotterm/vscode-simple-vim#1]
When I press `shift+F12` to list all references to a symbol, usually `ESC` closes the references pane. But with the simple vim extension installed, `ESC` doesn't close the references pane.

**Comment by jpotterm** [comment]
Thanks for the bug report! I'll see if there's a way to fix this. In the meantime you can use `Shift+Escape` to close it which doesn't conflict with SimpleVim.

**Comment by fengzhou0x** [comment]
I opened vscode today and somehow `ESC` can close reference pane now. Not sure what fixed it, but will close this issue.
