### ISSUE TITLE
Beginning of line keys `$` and `0`

### ISSUE THREAD

**Issue by canadaduane** [jpotterm/vscode-simple-vim#10]
I'm looking for a way to go to the beginning of the line, and I'm used using `$` to go to the first character in a line, and `0` to go to the very beginning of the line.

**Comment by jpotterm** [comment]
See the README for documentation: https://github.com/jpotterm/vscode-simple-vim/blob/master/README.md

`$` goes to the end of the line and `_` (underscore) goes to the beginning.

**Comment by canadaduane** [comment]
Sorry, I meant the caret ^ not the $

**Comment by jpotterm** [comment]
Ok, that makes more sense.

Underscore goes the first character of the line just like in Vim (Vim also supports `^` for this, but SimpleVim only supports `_`).

SimpleVim doesn't have any equivalent to Vim's `0` command which takes you to the beginning of the line before leading whitespace. I can't think of a use case for it, but if this is something you use often, let me know what you use it for.

**Comment by canadaduane** [comment]
I like that it doesn't require a "shift" key combination and I can word
jump from there.

I feel weird having to justify normal vim keys. I've found amVim to be
suitable and perhaps more ideologically aligned. Thanks for your time!

>
