### ISSUE TITLE
Yank and Paste don't work correctly

### ISSUE THREAD

**Issue by fengzhou0x** [jpotterm/vscode-simple-vim#2]
`Y` and `P` don't work correctly in normal mode. It seems to be only able to yank once.

**Comment by jpotterm** [comment]
Can you give more information? They seem to work for me. An example document and key sequence would be great.

**Comment by fengzhou0x** [comment]
I don't remember the exact key sequence, it seems to work fine. I'll either close this issue or provide reproduction steps in a couple of days.

**Comment by jpotterm** [comment]
I'm closing this because I couldn't reproduce it. If you run into this again then I'll reopen this or you can open a new issue.
