### ISSUE TITLE
`f` and `F` not working

### ISSUE THREAD

**Issue by abuisman** [jpotterm/vscode-simple-vim#25]
I want to use `f <char>` to jump to the next occurence of `<char>` on the line I am in, but nothing happens when I press it followed by a character.

**Comment by abuisman** [comment]
I just found out it is supposed to work like so: `f <char> <char>` I misread. 

How could I change the bindings in a fork to work with `f <char>`?

I found this line: 

```
createOperatorRangeRegex(/^f(..)$/, /^(f|f.)$/, false, (vimState, document, position, match) => {
```

But changing the regexes like so doesn't work:

```
createOperatorRangeRegex(/^f(.)$/, /^f$/
```

**Comment by abuisman** [comment]
I was editing the wrong file (operator_ranges), I needed to edit `motions`

**Comment by jpotterm** [comment]
@abuisman Yep, you got it! I'm glad you figured it out :-)
