### ISSUE TITLE
`delete` key in normal mode deletes character

### ISSUE THREAD

**Issue by fengzhou0x** [jpotterm/vscode-simple-vim#3]
Hitting `delete` in normal mode deletes characters, I think this is a bug? I don't remember how Vim handles `delete` in normal mode, but it shouldn't delete.

**Comment by jpotterm** [comment]
This is working as intended. If you don't want to delete a character, then don't hit the delete key. It differs from how Vim does it but I don't see a reason for Vim's way, and at the very least it's not important enough to add code specifically to intercept the delete key.
